server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@;?2021
    url: jdbc:mysql://39.97.224.12:3306/tcms_manage?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true
#    schema: classpath:db/schema.sql
mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.reige.developer.module

#showSql
logging:
  level:
    com:
      reige:
        developer: debug